services:
  deps:
    image: busybox
    depends_on:
      - server-pg

  server-pg:
    image: postgres:15.5
    ports: [ 5433:5432 ]
    environment: [ POSTGRES_USER=user, POSTGRES_PASSWORD=password, POSTGRES_DB=pg ]
    healthcheck: { test: ["CMD-SHELL", "pg_isready"], interval: 5s, timeout: 30s, retries: 5 }

  accorde:
    image: sandipndev/accorde
    ports: [ 3000:3000 ]
    depends_on: [ server-pg ]
    environment: [ PG_CON=postgresql://user:password@server-pg:5432/pg ]
