version: "3"
services:
  integration-deps:
    image: busybox
    depends_on:
      - server-pg
  server-pg:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  accorde:
    image: sandipndev/accorde
    ports:
      - "8765:8765"
    depends_on:
      - server-pg
    environment:
      - PG_CON=postgresql://user:password@server-pg:5432/pg"
