name: latest-tagged

on:
  workflow_dispatch:

jobs:
  latest-tagged:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cargo Semver Tool
        run: |
          rustup component add rustfmt
          cargo install cargo-release

      - name: Bump version and release
        id: version
        run: |
          cargo release patch --dry-run
          NEW_VERSION=$(grep -m 1 '^version' Cargo.toml | awk '{ print $3 }' | tr -d '"')
          echo "VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Push new tag to GitHub
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag v${{ env.VERSION }}
          git push --tags

      - name: Build and push Docker image with version tag
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/sandipndev/accorde:${{ env.VERSION }}
            ghcr.io/sandipndev/accorde:latest
